### ISSUE TITLE
Avif compression not implemented in proxy mode

### ISSUE THREAD

**Issue by bugfest** [webp-sh/webp_server_go#193]
**Describe the bug**
`webp_server_go` does not use AVIF compression when configured in proxy mode

**To Reproduce**
```yaml
{
    "IMG_PATH": "http://my.backend.server",
    "EXHAUST_PATH": "",
    "ENABLE_AVIF": true,
    ...
}
```

**Expected behavior**
I expect to get AVIF compressed images when provide better compression than WebP

**Screenshots and logs**
n/a

**Environment (please complete the following information):**
 - OS: Linux, MacOS
 - version or branch: 0.6.0

**Additional context**
n/a
