### ISSUE TITLE
webp-server uses to much memory

### ISSUE THREAD

**Issue by bhzhu203** [webp-sh/webp_server_go#198]
At the first time , it uses 1GB memory . But after 7 hours , it grows to 6.7GB and continue to grow slowly. 

![图片](https://github.com/webp-sh/webp_server_go/assets/3523160/0cfda962-c1c8-4d45-9408-c4399ce9f4a0)

**Comment by bhzhu203** [comment]
So , how to continue improve the memory usage ?

**Comment by n0vad3v** [comment]
Could you please have a try adding `MALLOC_ARENA_MAX=1` env before running the program?
Ref: https://github.com/davidbyttow/govips#memory-usage-note

In my testing case the RAM it used after benching using method from https://github.com/webp-sh/webp_server_go/pull/200, has reduced to less than 100MiB after testing:
```
eb5eff3296d1   webp-server-webp-1   0.04%     95.56MiB / 45.89GiB   0.20%     54.6kB / 11.9MB   98.3kB / 28.6MB   20
```

My docker-compose.yml example:
```
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    environment:
      - MALLOC_ARENA_MAX=1
    volumes:
      - ./pics:/opt/pics
      - ./exhaust:/opt/exhaust
    ports:
      -  127.0.0.1:3333:3333
    command: '/usr/bin/webp-server --config /etc/config.json -v'

```

**Comment by Ingiboy** [comment]
> Could you please have a try adding `MALLOC_ARENA_MAX=1` env before running the program? 
Yes, but it eat 1-2-3Gb.
I use `docker exec webp-http sh -c 'kill -HUP 1'` every 15 min

**Comment by n0vad3v** [comment]
@Ingiboy OK, that seems better.

BTW, you can use `docker-compose.yml` described in https://docs.webp.sh/usage/docker/ with resource limit so it will automatically restart if RAM has reached your limitation, instead of restarting it manually, example as below.

```
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    volumes:
      - ./path/to/pics:/opt/pics
      - ./path/to/exhaust:/opt/exhaust
    ports:
      -  127.0.0.1:3333:3333
    deploy:
      resources:
        limits:
          memory: 200M
```

Use with `docker-compose --compatibility up -d` to start.

**Comment by Ingiboy** [comment]
When i set deploy section with mem limit=512M, LA grows up to 30-40, CPU in wait state 60-80%. Without 'deploy' LA less 1.

**Comment by BennyThink** [comment]
that is because docker engine will try to kill and then restart the container quiet often, so high load average.

@n0vad3v can we consider adding back `MaxCacheMem`  and `MaxCacheSize`? We can read environment variables so it's totally up to end users.

**Comment by Ingiboy** [comment]
> that is because docker engine will try to kill and then restart the container quiet often, so high load average.

> No, i see 'docker ps' - container uptime is more than 6h. I think memlimit is limiting only RAM, and container eat the swap)

**Comment by n0vad3v** [comment]
@Ingiboy 
I've dig some more on https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details and found that:

> If --memory-swap is unset, and --memory is set, the container can use as much swap as the --memory setting, if the host container has swap memory configured. For instance, if --memory="300m" and --memory-swap is not set, the container can use 600m in total of memory and swap.

So using the `docker-compose.yml` as above:

```
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    volumes:
      - ./path/to/pics:/opt/pics
      - ./path/to/exhaust:/opt/exhaust
    ports:
      -  127.0.0.1:3333:3333
    deploy:
      resources:
        limits:
          memory: 200M
```

The container can use 200M of RAM and 200M of swap, can be confirmed by `docker inspect`

```
"Memory": 209715200,
...
"MemorySwap": 419430400,
```

In order to limit the swap usage, here is an working example(Note I've added MALLOC_ARENA_MAX in env):

```
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    restart: always
    environment:
      - MALLOC_ARENA_MAX=1
    volumes:
      - ./path/to/pics:/opt/pics
      - ./path/to/exhaust:/opt/exhaust
    ports:
      -  127.0.0.1:3333:3333

    deploy:
      resources:
        limits:
          memory: 200M
    memswap_limit: 200M
```

In this case, the container can use no swap and only 200M of RAM, and will restart the container if ram runs above 200M.

Example inspired by https://stackoverflow.com/questions/70095537/how-to-use-swap-memory-in-docker-compose, have to say the structure is wierd somehow, not sure why it is designed like that.

Please have a try on this, BTW, a higher ram limit than 512MB is suggested.

**Comment by Ingiboy** [comment]
@n0vad3v, o, thanks! i try it

**Comment by Ingiboy** [comment]
Hmm, don't helps.
```
version: "3.3"
services:
  webp-http:
    container_name: webp-http
    image: webpsh/webp-server-go:latest
    restart: unless-stopped
    user: 1001:1001
    cap_drop:
      - ALL
    environment:
      - MALLOC_ARENA_MAX=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./webp/config.json:/etc/config.json:ro
      - /var/tmp/webp-http/exhaust:/opt/exhaust
      - /var/tmp/webp-http/remote-raw:/opt/remote-raw
    ports:
     - 127.0.0.1:3335:3333
    deploy:
      resources:
        limits:
          memory: 196M
    memswap_limit: 196M
```
after some minuts LA grows up to 30-40, CPU in wa state about 80%. webp utilizes CPU more than 100%

**Comment by n0vad3v** [comment]
@Ingiboy 
> Hmm, don't helps.

Seems weird, in the compose file content provided above, in my understanding with `memswap_limit` set it should no write to swap, but you've described "CPU in wa state about 80%", are your images large or your machine's disk is quite slow, or if using VPS, might that be caused by CPU overselling?

May I have some more info on your case:

* What type of disk are you using? (HDD, SSD, NVMe SSD?) The disk type can have an impact on the overall performance, especially when dealing with I/O operations.
* When "LA grows up to 30-40, CPU in wa state about 80%. webp utilizes CPU more than 100%", it's important to understand the underlying reasons. Could you provide more details about the number of requests being sent to the service and the sizes of the images involved? This information will help in identifying potential bottlenecks.
* From your previous reply "Yes, but it eat 1-2-3Gb.", I'm assuming your machine has more than 3GB's RAM, if you raise `memory` and `memswap_limit` to, say 1024MB, what will happen after running?

**Comment by Ingiboy** [comment]
All not good) I tried to put memory=1G and memswap_limit=1G || memswap_limit=0. If the memory usage is about gigabyte - LA about 40, CPU wa about 80% etc(

**Comment by n0vad3v** [comment]
🤔 Kinda weird as I still cannot reproduce your issue in my local env, when setting memory and memswap_limit, my container gets instantly killed when RAM exceeds that value, with some failed requests and almost no high CPU spikes.

Have you tried maybe change a VPS provider or machine to have another test on similar scenario?

**Comment by Ingiboy** [comment]
May be it helps:
```
#docker -v
Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.3

```
```
# lsb_release -a
Description:    Ubuntu 18.04.6 LTS
```

Unfortunately i can't change server, because it prod

**Comment by Ingiboy** [comment]
Generally, it doesn't matter exactly how docker is restarted. webp-server - great tool, many thanks)
I'll wait until the memory leaks are fixed)

**Comment by bugfest** [comment]
So using this fixed config for `vips` makes my server not to crush (OOM killer) under load:
```diff
        vips.Startup(&vips.Config{
-               ConcurrencyLevel: runtime.NumCPU(),
+               ConcurrencyLevel: 1,
+               MaxCacheMem: 16 * 1024 * 1024,
+               MaxCacheSize: 16 * 1024 * 1024,
+               MaxCacheFiles: 128,
        })
```

But this is just a workaround; I'd say the solution is to solve #75, I'm now evaluating the following go-routine pool implementations:
- https://github.com/Jeffail/tunny
- https://github.com/panjf2000/ants

**Comment by n0vad3v** [comment]
Maybe we need to figure out how theses params affect the real performance, as in PR https://github.com/webp-sh/webp_server_go/pull/200 I've done some tests and said:

> However we need more information on MaxCacheMem and MaxCacheSize before considering merging this PR.

With @BennyThink 's reply
>vips_cache_set_max_mem() and vips_cache_get_max_mem(): These are functions that control the maximum amount of memory that libvips will use for caching. If a request to allocate more memory for caching comes in and it would cause libvips to exceed this limit, the cache is trimmed to stay under this limit. The size is in bytes.
vips_cache_set_max() and vips_cache_get_max(): These control the maximum number of operations that libvips will cache. If more operations are requested than this number, the least recently used operations are dropped from the cache. This is essentially a count of cached operations, not a size in bytes.
by chatgpt

I mean, if given the MaxCacheMem,MaxCacheSize,MaxCacheFiles above will have no performance impact to WebP Server, maybe we should just hard code it? (maybe leave some env for user to adjust them if they wish)

**Comment by n0vad3v** [comment]
I've done some benchmark on some photos (239 Photos, total 2.4GiB) using prefetch

***
Normal configuration:

```
	vips.Startup(&vips.Config{
		ConcurrencyLevel: runtime.NumCPU(),
	})
```

```
Prefetching... 100% |██████████████████████████████████████████████████████| (239/239, 11 it/s)         
Prefetch completeY(^_^)Y in 22.192475241s
```

![](https://github.com/webp-sh/webp_server_go/assets/24852034/f635f1ae-e98f-423b-9058-0dee90386d87)


***
bugfest configuration:
```
	vips.Startup(&vips.Config{
		ConcurrencyLevel: 1,
		MaxCacheMem:      16 * 1024 * 1024,
		MaxCacheSize:     16 * 1024 * 1024,
		MaxCacheFiles:    128,
	})
```
```
Prefetching... 100% |██████████████████████████████████████████████████████| (239/239, 12 it/s)         
Prefetch completeY(^_^)Y in 20.291148467s
```

![](https://github.com/webp-sh/webp_server_go/assets/24852034/f7a56d74-e524-47d0-a891-6612ed49aec5)

**Comment by Ingiboy** [comment]
> Sorry @n0vad3v I didn't mentioned I use it in proxy mode with AVIF enabled. 

Yes, me too use it in proxy mode, but without avif, only webp

**Comment by n0vad3v** [comment]
> Also, I don't know if we should develop some parallel test in which we benchmark edge-cases here; like concurrent images converstion with the max size allowed by the image format (64k x 64k)

Yeah, and I've been thinking of creating a testing website for proxy mode testing, like generating 200+ images and host it on a website for testing, but I have no idea on image source(especially when dealing with license).

**Comment by bugfest** [comment]
what about if we generate completely random/noise images (https://github.com/mathisve/GoRandomNoiseImage) on the fly so that we can benchmark/measure the conversion when running in parallel?

**Comment by bhzhu203** [comment]
1)
export MALLOC_ARENA_MAX=1
the memery is stable at 2.5G ~ 3G 


2)
export MALLOC_ARENA_MAX=1
export LD_PRELOAD=/libjemalloc.so

the memery is stable at 150m~204.2m .

Seems there is the best memery performance with jemalloc . Could webp-server link static with jemalloc lib ?

**Comment by n0vad3v** [comment]
> export LD_PRELOAD=/libjemalloc.so

Nice catch, I've done some local testing and found that `jemalloc` indeed uses less RAM. However will this have negative impact on stability or performance.

I saw some related discussion at: https://github.com/lovell/sharp/issues/955#issuecomment-663153909 and https://github.com/libvips/libvips/issues/1064#issuecomment-413978530.

Currently I'm planning to add jemalloc and tcmalloc to Dockerfile, and allow user using ENV for switching between those.

**Comment by Ingiboy** [comment]
In proxy mode on prod:
```
version: "3.3"

services:
  webp:
    container_name: webp
    image: webpsh/webp-server-go:0.8.4
    restart: unless-stopped
    user: 1001:1001
    cap_drop:
      - ALL
    environment:
      - MALLOC_ARENA_MAX=1
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
#      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./webp/config.json:/etc/config.json:ro
      - /var/tmp/webp/exhaust:/opt/exhaust
      - /var/tmp/webp/remote-raw:/opt/remote-raw
    ports:
     - 127.0.0.1:3335:3333
```
![image](https://github.com/webp-sh/webp_server_go/assets/20064139/4a81a71d-4247-4a5d-a3c8-df3c15bb5c7c)
![image](https://github.com/webp-sh/webp_server_go/assets/20064139/9039425c-c5e7-4bab-a446-be0644476ff4)
