### ISSUE TITLE
Webp v0.9.3 is consuming a lot of memory again

### ISSUE THREAD

**Issue by Ingiboy** [webp-sh/webp_server_go#253]
Webp used both for converting to webp and resizing pictures. ~83k requests per day. Щn version 0.8.4 was consistently below 0.5gb

![image](https://github.com/webp-sh/webp_server_go/assets/20064139/ad6b0f5d-6ab2-4d41-b74c-724ded272afa)

docker-compose.yml
```
version: "3.3"

services:
  webp:
    container_name: webp
    image: webp:alpine
    build:
      context: webp
      dockerfile: Dockerfile
      args:
        - UID=1001
        - GID=1001
        - REPO=https://github.com/webp-sh/webp_server_go.git
        - TAG=0.9.3
    restart: unless-stopped
    user: 1001:1001
    cap_drop:
      - ALL
    environment:
      - MALLOC_ARENA_MAX=1
      - LD_PRELOAD=/usr/lib/libjemalloc.so.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./webp/config.json:/etc/config.json:ro
      - /var/tmp/webp:/opt
    ports:
     - 127.0.0.1:3335:3333
```

Dockerfile:
```
FROM alpine:3.18 as builder

ARG REPO
ARG TAG

RUN set -ex && \
    apk --update upgrade --no-cache && \
    apk --update add --no-cache git go vips-dev && \
    mkdir /build && \
    cd /build && \
    git clone ${REPO} . && \
    git checkout tags/${TAG} && \
    go mod download && \
    go build -ldflags="-s -w" -o webp-server .


FROM alpine:3.18

ARG UID
ARG GID

RUN set -ex && \
    addgroup -g ${GID} user && adduser -u ${UID} -G user -s /bin/sh -D user && \
    apk --update upgrade --no-cache && \
    apk --update add --no-cache vips ca-certificates jemalloc

COPY --from=builder /build/webp-server  /usr/bin/webp-server
COPY --from=builder /build/config.json /etc/config.json

WORKDIR /opt

CMD ["/usr/bin/webp-server", "--config", "/etc/config.json"]
```

config.json:
```
{
  "HOST": "0.0.0.0",
  "PORT": "3333",
  "QUALITY": "80",
  "MAX_JOB_COUNT": "4",
  "IMG_PATH": "http://nginx:8080",
  "EXHAUST_PATH": "./exhaust",
  "ALLOWED_TYPES": ["jpg","png","jpeg","bmp"],
  "ENABLE_EXTRA_PARAMS": true,
  "ENABLE_AVIF": false
}
```
