### ISSUE TITLE
When the instantaneous request volume is large, a large amount of CPU and memory will be consumed.

### ISSUE THREAD

**Issue by mikusaa** [webp-sh/webp_server_go#306]
**Describe the bug**
When the instantaneous request volume is large, a large amount of CPU and memory will be consumed.

**To Reproduce**
It seems that when using Webpgo on my blog, which includes webp, jpg, and png images, a fresh installation of Webpgo may experience delays in compressing images due to a high request volume. This delay is causing a significant increase in CPU and memory usage.

here is the compose.yml
```
  webpgo:
    image: webpsh/webp-server-go
    environment:
      - MALLOC_ARENA_MAX=1
      - TZ=Asia/Shanghai
    volumes:
      - ./webpgo/config.json:/etc/config.json
      - ./static:/opt/pics
      - ./webpgo/exhaust:/opt/exhaust
      - ./webpgo/metadata:/opt/metadata
    ports:
      - 3333:3333
    restart: unless-stopped
    container_name: webpgo
```
and the config.json
```
{
    "HOST": "0.0.0.0",
    "PORT": "3333",
    "QUALITY": "75",
    "IMG_PATH": "/opt/pics",
    "IMG_MAP": {},
    "EXHAUST_PATH": "./exhaust",
    "ALLOWED_TYPES": ["jpg","png","jpeg","bmp","gif","svg","webp","heic"],
    "ENABLE_AVIF": true,
    "ENABLE_EXTRA_PARAMS": true
  }
```

**Expected behavior**

**Screenshots and logs**
HTOP
![image](https://github.com/webp-sh/webp_server_go/assets/31799398/376a66b8-046b-484e-881a-c916878870f7)
VNC
![image](https://github.com/webp-sh/webp_server_go/assets/31799398/5430320c-0b28-4c7f-9a93-a4e2ed76579d)

Then, my server becomes unresponsive.

**Environment (please complete the following information):**
 - OS: Debian 12 ,With a CPU of 4 cores and a memory capacity of 4GB
 - version or branch: v0.10.4

**Additional context**
None
