### ISSUE TITLE
多路径域名识别错误

### ISSUE THREAD

**Issue by ihufu** [webp-sh/webp_server_go#336]
**Describe the bug**
多路径域名识别错误

**To Reproduce**
"/hi": "https://hi.baidu.com",
"/hi1": "http://hi1.baiducom"

设置成这样访问hi1 会出现域名识别错误

**Screenshots and logs**
time="2024-06-05 05:57:36" level=info msg="Remote Addr is https://hi.baidu.com1/xxx/6fcede879b3a36b2afc2bd9e3c97987f.jpg, pinging for info..." func="[96:webp_server_go/handler.fetchRemoteImg]"

**Environment (please complete the following information):**
 - OS: Linux
 - version or branch[0.11.3, master]

如日志显示，他识别的域名是hi这个映射的后面还加上了个1

**Comment by ihufu** [comment]
我用的是.cc的域名，远程获取又变成这样了，Remote Addr is https://hi.xxx.ccm/storage
这是要补齐三位的后缀吗？

**Comment by n0vad3v** [comment]
请提供完整 `config.json` 文件和本地所使用的 WebP Server Go 程序版本以及运行方式.

**Comment by ihufu** [comment]
{
  "HOST": "0.0.0.0",
  "PORT": "3333",
  "QUALITY": "80",
  "IMG_PATH": "",
  "EXHAUST_PATH": "./exhaust",
  "IMG_MAP": {
      "/fmg1": "https://fmg1.xxx.net",
      "/hi1": "http://hi1.xx.cc"
  },
  "ALLOWED_TYPES": ["jpg","png","jpeg","gif","bmp","svg","heic","nef"],
  "CONVERT_TYPES": ["webp"],
  "STRIP_METADATA": true,
  "ENABLE_EXTRA_PARAMS": false,
  "READ_BUFFER_SIZE": 4096,
  "CONCURRENCY": 262144,
  "DISABLE_KEEPALIVE": false,
  "CACHE_TTL": 259200
}

我的运行方式是docker  0.11.3 版本

**Comment by n0vad3v** [comment]
根据你所提供的 `config.json`：
```json
{
  "HOST": "0.0.0.0",
  "PORT": "3333",
  "QUALITY": "80",
  "IMG_PATH": "",
  "EXHAUST_PATH": "./exhaust",
  "IMG_MAP": {"/fmg1": "https://fmg1.xxx.net", "/hi1": "http://hi1.xx.cc"},
  "ALLOWED_TYPES": ["jpg", "png", "jpeg", "gif", "bmp", "svg", "heic", "nef"],
  "CONVERT_TYPES": ["webp"],
  "STRIP_METADATA": true,
  "ENABLE_EXTRA_PARAMS": false,
  "READ_BUFFER_SIZE": 4096,
  "CONCURRENCY": 262144,
  "DISABLE_KEEPALIVE": false,
  "CACHE_TTL": 259200
}
```

我尝试在本地复现，使用如下 `docker-compose.yml` 文件：
```yml
version: '3'

services:
  webp:
    image: webpsh/webp-server-go:0.11.3
    restart: always
    volumes:
      - ./pics:/opt/pics
      - ./exhaust:/opt/exhaust
      - ./metadata:/opt/metadata
      - ./config.json:/etc/config.json
    ports:
      -  127.0.0.1:3333:3333
    command: '/usr/bin/webp-server --config /etc/config.json'
```

未能复现你的问题，在访问 `http://localhost:3333/hi1/path/to/image.jpg` 时，容器中 Log 如下：
```
...
time="2024-06-06 02:19:53" level=info msg="Remote Addr is http://hi1.xx.cc/path/to/image.jpg, pinging for info..." func="[96:webp_server_go/handler.fetchRemoteImg]"
time="2024-06-06 02:19:54" level=info msg="Remote didn't return etag in header when getRemoteImageInfo, please check." func="[138:webp_server_go/handler.pingURL]"
...
```
