### ISSUE TITLE
MultiPath(IMG_MAP) not working

### ISSUE THREAD

**Issue by junyangfan** [webp-sh/webp_server_go#349]
I am very happy to have used such a great project, but I encountered a problem while using it and hope to receive an answer.

My folder is as follows：
```
root@debian:~/webpgo# ls
config.json  docker-compose.yml   pics
```

The pics folder contains a `test-1.png` image

docker-compose.yml
```
version: '3'

services:
  webpgo:
    container_name: webpgo
    image: webpsh/webp-server-go
    restart: always
    volumes:
      - ./pics:/opt/pics
      - ./exhaust:/opt/exhaust
      - ./metadata:/opt/metadata
      - ./config.json:/etc/config.json
    ports:
      -  "23333:3333"
```

config.json

```
{
  "HOST": "0.0.0.0",
  "PORT": "3333",
  "QUALITY": "90",
  "IMG_PATH": "",
  "EXHAUST_PATH": "/opt/exhaust",
  "IMG_MAP": {
    "/images": "/opt/pics"
  },
  "ALLOWED_TYPES": ["jpg", "png", "jpeg", "bmp", "gif", "svg", "heic", "nef", "webp"],
  "CONVERT_TYPES": ["webp"],
  "STRIP_METADATA": true,
  "ENABLE_EXTRA_PARAMS": true,
  "EXTRA_PARAMS_CROP_INTERESTING": "InterestingAttention",
  "READ_BUFFER_SIZE": 4096,
  "CONCURRENCY": 262144,
  "DISABLE_KEEPALIVE": false,
  "CACHE_TTL": 259200,
  "MAX_CACHE_SIZE": 0,
}
```

When I start the service with the `docker compose up - d` command, And after configuring the basic nginx reverse proxy

```
server {
  server_name example.com;
  listen 443 ssl;
  http2 on;
  ssl_certificate xxx.cer;
  ssl_certificate_key xxx.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  listen 80;
  if ($scheme = http) {
    return 301 https://$host:443$request_uri;
  }
  location / {
    proxy_pass http://127.0.0.1:23333;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect http:// https://;
  }
}

```

`https://example.com/images/test-1.png` not working，tip: `Image not found!`

`https://example.com/test-1.png` is working，

Why did this situation occur, expected `https://example.com/images/test-1.png` is working,`https://example.com/test-1.png` not working.

I am using the latest webpsh/webp-server-go image

And I want to use it with my self built Minio S3 storage service. How should I proceed?

I am very confused about this and hope to receive an answer,thanks
